### ISSUE TITLE
Ventilation cases on 11 May

### ISSUE THREAD

**Issue by CHLAI0410** [wnarifin/covid-19-malaysia#1]
Ventilation cases shown on MOH website on 11 May is 224 instead of 244 on kpk report 
[http://covid-19.moh.gov.my/terkini/2021/05/situasi-terkini-covid-19-di-malaysia-11052021](url)

**Comment by wnarifin** [comment]
The data from KPK report was referred to instead of MOH website (http://covid-19.moh.gov.my), i.e. 244. The PDF version of the report from MOH website also stated 244 instead of 224.
